import * as React from "react";
import TextField from "@mui/material/TextField";
import Autocomplete from "@mui/material/Autocomplete";

const data = [
  { label: "#살아있다" },
  { label: "0.0MHz" },
  { label: "007 스카이폴" },
  { label: "007 스펙터" },
  { label: "007 제21탄 - 카지노 로얄" },
  { label: "007 퀀텀 오브 솔러스" },
  { label: "10,000BC" },
  { label: "100 피트" },
  { label: "10억" },
  { label: "13구역: 얼티메이텀" },
  { label: "1917" },
  { label: "1987" },
  { label: "19곰 테드" },
  { label: "19곰 테드 2" },
  { label: "1급기밀" },
  { label: "1번가의 기적" },
  { label: "2012" },
  { label: "21" },
  { label: "23 아이덴티티" },
  { label: "26년" },
  { label: "300" },
  { label: "300: 제국의 부활" },
  { label: "4.4.4." },
  { label: "47 미터" },
  { label: "47미터 2" },
  { label: "50/50" },
  { label: "500일의 썸머" },
  { label: "50가지 그림자: 해방" },
  { label: "577 프로젝트" },
  { label: "69세" },
  { label: "6월의 일기" },
  { label: "7광구" },
  { label: "7급 공무원" },
  { label: "7년의 밤" },
  { label: "7번방의 선물" },
  { label: "82년생 김지영" },
  { label: "88분" },
  { label: "8인: 최후의 결사단" },
  { label: "A-특공대" },
  { label: "BB 프로젝트" },
  { label: "B형 남자친구" },
  { label: "CJ7 - 장강7호" },
  { label: "M" },
  { label: "MB의 추억" },
  { label: "Mr. 히치 - 당신을 위한 데이트 코치" },
  { label: "PM 11:14" },
  { label: "PMC: 더 벙커" },
  { label: "R.I.P.D. : 알.아이.피.디." },
  { label: "가디언의 전설" },
  { label: "가디언즈" },
  { label: "가디언즈 오브 갤럭시" },
  { label: "가디언즈 오브 갤럭시 VOL. 2" },
  { label: "가려진 시간" },
  { label: "가루지기" },
  { label: "가면" },
  { label: "가문의 부활 - 가문의 영광 3" },
  { label: "가문의 영광5-가문의 귀환" },
  { label: "가문의 위기 - 가문의 영광 2" },
  { label: "가시" },
  { label: "가을로" },
  { label: "가장 보통의 연애" },
  { label: "각설탕" },
  { label: "간기남" },
  { label: "간신" },
  { label: "간첩" },
  { label: "감기" },
  { label: "감시자들" },
  { label: "감자 심포니" },
  { label: "강남 1970" },
  { label: "강력3반" },
  { label: "강적" },
  { label: "강철대오: 구국의 철가방" },
  { label: "강철비" },
  { label: "강철비2: 정상회담" },
  { label: "강철중: 공공의 적 1-1" },
  { label: "개들의 전쟁" },
  { label: "개를 훔치는 완벽한 방법" },
  { label: "거룩한 계보" },
  { label: "거미줄에 걸린 소녀" },
  { label: "거북이 달린다" },
  { label: "거칠마루" },
  { label: "건축학개론" },
  { label: "걸리버 여행기" },
  { label: "걸캅스" },
  { label: "검객" },
  { label: "검사외전" },
  { label: "검은 사제들" },
  { label: "검은 집" },
  { label: "게이머" },
  { label: "게이샤의 추억" },
  { label: "겟 스마트" },
  { label: "겟 썸" },
  { label: "겟 아웃" },
  { label: "겨울왕국" },
  { label: "겨울왕국 2" },
  { label: "결백" },
  { label: "결혼전야" },
  { label: "경성학교: 사라진 소녀들" },
  { label: "경축! 우리 사랑" },
  { label: "계춘할망" },
  { label: "고사 두 번째 이야기: 교생실습" },
  { label: "고사: 피의 중간고사" },
  { label: "고산자, 대동여지도" },
  { label: "고스트버스터즈" },
  { label: "고양이: 죽음을 보는 두 개의 눈" },
  { label: "고지전" },
  { label: "고질라: 킹 오브 몬스터" },
  { label: "곡성(哭聲)" },
  { label: "곤지암" },
  { label: "골든 에이지" },
  { label: "골든슬럼버" },
  { label: "공각기동대 : 고스트 인 더 쉘" },
  { label: "공공의 적 2" },
  { label: "공기인형" },
  { label: "공모자들" },
  { label: "공범" },
  { label: "공범자들" },
  { label: "공작" },
  { label: "공조" },
  { label: "과속스캔들" },
  { label: "관상" },
  { label: "광대들: 풍문조작단" },
  { label: "광식이 동생 광태" },
  { label: "광해, 왕이 된 남자" },
  { label: "괴물" },
  { label: "괴물의 아이" },
  { label: "교회오빠" },
  { label: "구르믈 버서난 달처럼" },
  { label: "구세주" },
  { label: "구세주 2" },
  { label: "국가대표" },
  { label: "국가부도의 날" },
  { label: "국제수사" },
  { label: "국제시장" },
  { label: "군도:민란의 시대" },
  { label: "군함도" },
  { label: "굿 셰퍼드" },
  { label: "굿' 바이: Good & Bye" },
  { label: "굿모닝 프레지던트" },
  { label: "굿바이 싱글" },
  { label: "궁녀" },
  { label: "궁합" },
  { label: "권순분 여사 납치사건" },
  { label: "귀천도" },
  { label: "귀향" },
  { label: "그 남자의 책 198쪽" },
  { label: "그 여자 작사 그 남자 작곡" },
  { label: "그것만이 내 세상" },
  { label: "그날, 바다" },
  { label: "그날의 분위기" },
  { label: "그녀" },
  { label: "그놈 목소리" },
  { label: "그놈이다" },
  { label: "그는 당신에게 반하지 않았다" },
  { label: "그대를 사랑합니다" },
  { label: "그때 그사람들" },
  { label: "그랑블루" },
  { label: "그래비티" },
  { label: "그랜드 부다페스트 호텔" },
  { label: "그레이의 50가지 그림자" },
  { label: "그루지" },
  { label: "그린 북" },
  { label: "그린 존" },
  { label: "그린 호넷" },
  { label: "그린랜드" },
  { label: "그림 형제 - 마르바덴 숲의 전설" },
  { label: "그림자 살인" },
  { label: "그물" },
  { label: "그집" },
  { label: "그해 여름" },
  { label: "극락도 살인사건" },
  { label: "극비수사" },
  { label: "극장판 짱구는 못말려 : 습격!! 외계인 덩덩이" },
  { label: "극장판 짱구는 못말려: 신혼여행 허리케인~ 사라진 아빠!" },
  { label: "극장판 포켓 몬스터 DP - 아르세우스 초극의 시공으로" },
  { label: "극장판 포켓몬스터 너로 정했다!" },
  { label: "극장판 포켓몬스터 뮤츠의 역습 EVOLUTION" },
  { label: "극장판 포켓몬스터 베스트위시 : 비크티니와 흑의 영웅 제크로무" },
  { label: "극한직업" },
  { label: "글래스" },
  { label: "글러브" },
  { label: "글로리데이" },
  { label: "기생수 파트1" },
  { label: "기생충" },
  { label: "기술자들" },
  { label: "기억의 밤" },
  { label: "기프트" },
  { label: "김광석" },
  { label: "김씨 표류기" },
  { label: "깡철이" },
  { label: "꼬마 니콜라" },
  { label: "꼭두각시" },
  { label: "꽃미남 연쇄 테러사건" },
  { label: "꾸뻬씨의 행복여행" },
  { label: "꾼" },
  { label: "꿈은 이루어진다" },
  { label: "끝과 시작" },
  { label: "끝까지 간다" },
  { label: "나나" },
  { label: "나는 갈매기" },
  { label: "나는 공무원이다" },
  { label: "나는 비와 함께 간다" },
  { label: "나는 전설이다" },
  { label: "나니아 연대기 - 사자, 마녀 그리고 옷장" },
  { label: "나니아 연대기 - 캐스피언 왕자" },
  { label: "나랏말싸미" },
  { label: "나를 기억해" },
  { label: "나를 차버린 스파이" },
  { label: "나를 찾아줘" },
  { label: "나를 찾아줘" },
  { label: "나쁜 녀석들 : 포에버" },
  { label: "나쁜 녀석들: 더 무비" },
  { label: "나우 유 씨 미 2" },
  { label: "나우 유 씨 미 : 마술사기단" },
  { label: "나의 PS 파트너" },
  { label: "나의 결혼 원정기" },
  { label: "나의 독재자" },
  { label: "나의 사랑 나의 신부" },
  { label: "나의 절친 악당들" },
  { label: "나의 청춘은 너의 것" },
  { label: "나의 특별한 형제" },
  { label: "나이브스 아웃" },
  { label: "나이트메어" },
  { label: "나인" },
  { label: "나잇 & 데이" },
  { label: "나탈리" },
  { label: "날, 보러와요" },
  { label: "날씨의 아이" },
  { label: "날아라 허동구" },
  { label: "남과 여" },
  { label: "남극일기" },
  { label: "남매의 여름밤" },
  { label: "남산의 부장들" },
  { label: "남영동1985" },
  { label: "남자가 사랑할 때" },
  { label: "남자사용설명서" },
  { label: "남한산성" },
  { label: "내 깡패 같은 애인" },
  { label: "내 사랑" },
  { label: "내 사랑" },
  { label: "내 사랑 내 곁에" },
  { label: "내 생애 가장 아름다운 일주일" },
  { label: "내 생애 최악의 남자" },
  { label: "내 심장을 쏴라" },
  { label: "내 아내의 모든 것" },
  { label: "내 여자의 남자친구" },
  { label: "내 이름은 칸" },
  { label: "내가 살인범이다" },
  { label: "내부자들" },
  { label: "내부자들: 디 오리지널" },
  { label: "내셔널 트레져: 비밀의 책" },
  { label: "내안의 그놈" },
  { label: "냉정과 열정 사이" },
  { label: "너는 내 운명" },
  { label: "너를 잊지 않을 거야" },
  { label: "너와 100번째 사랑" },
  { label: "너의 결혼식" },
  { label: "너의 이름은." },
  { label: "너의 췌장을 먹고 싶어" },
  { label: "널 기다리며" },
  { label: "넘버 23" },
  { label: "넛잡: 땅콩 도둑들" },
  { label: "네버랜드를 찾아서" },
  { label: "네버엔딩 스토리" },
  { label: "넥스트" },
  { label: "노리개" },
  { label: "노무현입니다" },
  { label: "노브레싱" },
  { label: "노아" },
  { label: "노예 12년" },
  { label: "노인을 위한 나라는 없다" },
  { label: "노잉" },
  { label: "노크: 낯선 자들의 방문" },
  { label: "노트북" },
  { label: "노팅 힐" },
  { label: "논스톱" },
  { label: "누가 그녀와 잤을까?" },
  { label: "눈먼 자들의 도시" },
  { label: "눈물" },
  { label: "눈부신 날에" },
  { label: "눈에는 눈 이에는 이" },
  { label: "눈의 여왕2: 트롤의 마법거울" },
  { label: "눈의 여왕4" },
  { label: "뉴 문" },
  { label: "늑대소년" },
  { label: "늑대아이" },
  { label: "니벨룽겐의 반지" },
  { label: "닌자 어쌔신" },
  { label: "닌자터틀" },
  { label: "님스 아일랜드" },
  { label: "님아, 그 강을 건너지 마오" },
  { label: "님은 먼곳에" },
  { label: "다만 악에서 구하소서" },
  { label: "다빈치 코드" },
  { label: "다세포 소녀" },
  { label: "다이 하드 4.0" },
  { label: "다이버전트" },
  { label: "다찌마와 리 - 악인이여 지옥행 급행열차를 타라!" },
  { label: "다크 나이트" },
  { label: "다크 나이트 라이즈" },
  { label: "다크 워터스" },
  { label: "다크타워: 희망의 탑" },
  { label: "닥터" },
  { label: "닥터 두리틀" },
  { label: "닥터 스트레인지" },
  { label: "달콤, 살벌한 연인" },
  { label: "달콤한 인생" },
  { label: "담보" },
  { label: "당갈" },
  { label: "당신, 거기 있어줄래요" },
  { label: "대립군" },
  { label: "대배우" },
  { label: "대병소장" },
  { label: "대장 김창수" },
  { label: "대한민국 1%" },
  { label: "대호" },
  { label: "댄 인 러브" },
  { label: "댄서의 순정" },
  { label: "댄싱퀸" },
  { label: "더 게임" },
  { label: "더 그레이" },
  { label: "더 넌" },
  { label: "더 라스트: 나루토 더 무비" },
  { label: "더 라이트: 악마는 있다" },
  { label: "더 리더 - 책 읽어주는 남자" },
  { label: "더 문" },
  { label: "더 보이" },
  { label: "더 울버린" },
  { label: "더 웹툰: 예고살인" },
  { label: "더 임파서블" },
  { label: "더 콘서트" },
  { label: "더 콜" },
  { label: "더 킥" },
  { label: "더 킹" },
  { label: "더 테러 라이브" },
  { label: "더 파이브" },
  { label: "더 퍼지:거리의 반란" },
  { label: "더 페이버릿: 여왕의 여자" },
  { label: "더 폰" },
  { label: "더 플랜" },
  { label: "더 플랫폼" },
  { label: "더블" },
  { label: "더블 타겟" },
  { label: "덕 패밀리" },
  { label: "덕혜옹주" },
  { label: "덤 앤 더머 투" },
  { label: "덤보" },
  { label: "덩케르크" },
  { label: "데드풀" },
  { label: "데드풀 2" },
  { label: "데스 노트" },
  { label: "데스 노트 - L: 새로운 시작" },
  { label: "데스 노트 - 라스트 네임" },
  { label: "데스 디파잉: 어느 마술사의 사랑" },
  { label: "데스노트: 더 뉴 월드" },
  { label: "데이지" },
  { label: "데자뷰" },
  { label: "데자뷰" },
  { label: "도가니" },
  { label: "도둑들" },
  { label: "도레미파솔라시도" },
  { label: "도리를 찾아서" },
  { label: "도리화가" },
  { label: "도마뱀" },
  { label: "도어락" },
  { label: "도쿄 타워" },
  { label: "도쿄 타워" },
  { label: "독전" },
  { label: "돈" },
  { label: "돈 크라이 마미" },
  { label: "돈비 어프레이드-어둠 속의 속삭임" },
  { label: "돈의 맛" },
  { label: "돌연변이" },
  { label: "동갑내기 과외하기 레슨 2" },
  { label: "동네사람들" },
  { label: "동주" },
  { label: "두 남자" },
  { label: "두 번의 결혼식과 한 번의 장례식" },
  { label: "두 얼굴의 여친" },
  { label: "두번째 사랑" },
  { label: "드라이브 앵그리 3D" },
  { label: "드래곤 길들이기" },
  { label: "드래곤 길들이기 2" },
  { label: "드래곤 길들이기 3" },
  { label: "드래곤볼Z : 신들의 전쟁" },
  { label: "드래그 미 투 헬" },
  { label: "드림걸즈" },
  { label: "들어는 봤니? 모건 부부" },
  { label: "디 인터뷰" },
  { label: "디-워" },
  { label: "디바" },
  { label: "디바이드" },
  { label: "디센트" },
  { label: "디스 민즈 워" },
  { label: "디스터비아" },
  { label: "디스트릭트 9" },
  { label: "디파티드" },
  { label: "딥워터 호라이즌" },
  { label: "똥파리" },
  { label: "뜨거운 것이 좋아" },
  { label: "뜨거운 녀석들" },
  { label: "뜨거운 안녕" },
  { label: "라디오 스타" },
  { label: "라따뚜이" },
  { label: "라라랜드" },
  { label: "라스베가스에서만 생길 수 있는 일" },
  { label: "라스트 갓파더" },
  { label: "라스트 스탠드" },
  { label: "라스트 에어벤더" },
  { label: "라스트 엑소시즘: 잠들지 않는 영혼" },
  { label: "라스트 위치 헌터" },
  { label: "라이온 킹" },
  { label: "라이온 킹 3D" },
  { label: "라이트 아웃" },
  { label: "라이프 오브 파이" },
  { label: "라파예트" },
  { label: "라푼젤" },
  { label: "람보 : 라스트 워" },
  { label: "램페이지" },
  { label: "러브 & 드럭스" },
  { label: "러브 & 트러블" },
  { label: "러브 유어셀프 인 서울" },
  { label: "러브픽션" },
  { label: "러블리 본즈" },
  { label: "러빙 빈센트" },
  { label: "럭키" },
  { label: "럭키 넘버 슬레븐" },
  { label: "런 올 나이트" },
  { label: "런닝맨" },
  { label: "런던 해즈 폴른" },
  { label: "레드 라이딩 후드" },
  { label: "레드: 더 레전드" },
  { label: "레드슈즈" },
  { label: "레드카펫" },
  { label: "레디 플레이어 원" },
  { label: "레모니 스니켓의 위험한 대결" },
  { label: "레미제라블" },
  { label: "레버넌트: 죽음에서 돌아온 자" },
  { label: "레이" },
  { label: "레전드 오브 조로" },
  { label: "레전드 오브 타잔" },
  { label: "레지던트 이블 3 - 인류의 멸망" },
  { label: "레지던트 이블 4: 끝나지 않은 전쟁 3D" },
  { label: "레지던트 이블: 파멸의 날" },
  { label: "레터스 투 줄리엣" },
  { label: "레플리카" },
  { label: "로건" },
  { label: "로그 원: 스타워즈 스토리" },
  { label: "로마 위드 러브" },
  { label: "로맨틱 헤븐" },
  { label: "로맨틱 홀리데이" },
  { label: "로보캅" },
  { label: "로봇" },
  { label: "로봇, 소리" },
  { label: "로빈 후드" },
  { label: "론 서바이버" },
  { label: "롱 리브 더 킹: 목포 영웅" },
  { label: "롱 샷" },
  { label: "루시" },
  { label: "루퍼" },
  { label: "리딕" },
  { label: "리얼" },
  { label: "리얼 스틸" },
  { label: "리오" },
  { label: "리틀 포레스트" },
  { label: "리핑 - 10개의 재앙" },
  { label: "립반윙클의 신부" },
  { label: "링컨 : 뱀파이어 헌터" },
  { label: "링컨 차를 타는 변호사" },
  { label: "마고리엄의 장난감 백화점" },
  { label: "마녀" },
  { label: "마다가스카" },
  { label: "마담 뺑덕" },
  { label: "마담 프루스트의 비밀정원" },
  { label: "마당을 나온 암탉" },
  { label: "마더" },
  { label: "마루 밑 아리에티" },
  { label: "마마" },
  { label: "마법사의 제자" },
  { label: "마션" },
  { label: "마스터" },
  { label: "마약왕" },
  { label: "마음이 2" },
  { label: "마음이..." },
  { label: "마이 블랙 미니드레스" },
  { label: "마이 스파이" },
  { label: "마이웨이" },
  { label: "마이클 잭슨의 디스 이즈 잇" },
  { label: "마파도" },
  { label: "만추" },
  { label: "말레피센트" },
  { label: "히트맨" },
];

export default function ComboBox() {
  return (
    <Autocomplete
      disablePortal
      id="combo-box-demo"
      options={data}
      sx={{ width: 300 }}
      renderInput={(params) => <TextField {...params} label="Songs" />}
    />
  );
}
